#include <stdio.h>
#include <console.h>

void kmain(){
	__InitializeTerminal();
	putk("=\n");
	putk(">\n");
	putk("?\n");
	putk("@\n");
	putk("A\n");
	putk("B\n");
	putk("C\n");
	putk("D\n");
	putk("E\n");
	putk("F\n");
	putk("G\n");
	putk("H\n");
	putk("I\n");
	putk("J\n");
	putk("K\n");
	putk("L\n");
	putk("M\n");
	putk("N\n");
	putk("O\n");
	putk("P\n");
	putk("Q\n");
	putk("R\n");
	putk("S\n");
	putk("T\n");
	putk("U\n");
	putk("V\n");
	putk("W\n");
	putk("X\n");
	putk("Y\n");
	putk("Z\n");
	putk("[\n");
	putk("\\n");
	putk("]\n");
	putk("^\n");
	putk("_\n");
	putk("`\n");
	putk("a\n");
	putk("b\n");
	putk("c\n");
	putk("d\n");
	putk("e\n");
	putk("f\n");
	putk("g\n");
	putk("h\n");
	putk("i\n");
	putk("j\n");
	putk("k\n");
	putk("l\n");
	putk("akjakakdhlaasdascvcdvcvskdvshjjjjjjjjjjjjjjjjsasllgsdcadfonhsochofhuxwmurfzadvbfbnvsnxfm\n");
	putk("n\n");
	putk("o");
	putk("p\n");
	putk("q\n");
	putk("r\n");
	putk("s\n");
	putk("t\n");
	putk("u\n");
	putk("v\n");
	putk("w\n");
	putk("x\n");
	putk("y\n");
	putk("dvfmlvhfmhvs,azqzzqavfblhjkjjjjjjjjjjkdsv;j;fvfmb[iaj,xqazq[.xrxcddkkkksd sdnvslfvsvjsvjjpjwspojjjfbslfz\n");

}